on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}